/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Approve_Control: typeof import('./components/pages/Public/Approve_Control.vue')['default']
    Brand: typeof import('./components/pages/Public/Brand.vue')['default']
    Brand_List: typeof import('./components/pages/Public/Brand_List.vue')['default']
    City: typeof import('./components/pages/Public/City.vue')['default']
    City_List: typeof import('./components/pages/Public/City_List.vue')['default']
    Customer: typeof import('./components/pages/Sales/Customer/Customer.vue')['default']
    Customer_List: typeof import('./components/pages/Sales/Customer/Customer_List.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Factory: typeof import('./components/pages/Production/Factory.vue')['default']
    Form_login: typeof import('./components/pages/Public/Form_login.vue')['default']
    Funds_Request_Edit: typeof import('./components/pages/Purchasing/Material/Funds_Request_Edit.vue')['default']
    Funds_Request_List: typeof import('./components/pages/Purchasing/Material/Funds_Request_List.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Knowledge: typeof import('./components/pages/Public/Knowledge.vue')['default']
    Manufacturer: typeof import('./components/pages/Production/Manufacturer.vue')['default']
    Manufacturer_List: typeof import('./components/pages/Production/Manufacturer_List.vue')['default']
    MyCKContents: typeof import('./components/pages/Public/myCKContents.vue')['default']
    MyCKEditor: typeof import('./components/pages/Public/myCKEditor.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    NaiveProviderTools: typeof import('./components/naiveProviderTools.vue')['default']
    Navigate_Menu: typeof import('./components/pages/Public/Navigate_Menu.vue')['default']
    Organization: typeof import('./components/pages/System/Organization.vue')['default']
    Organization_List: typeof import('./components/pages/System/Organization_List.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    Permission: typeof import('./components/pages/Public/Permission.vue')['default']
    Produce_Line: typeof import('./components/pages/Production/Produce_Line.vue')['default']
    Product_Size: typeof import('./components/pages/Public/Product_Size.vue')['default']
    Production_Progress_List: typeof import('./components/pages/Production/Production_Progress_List.vue')['default']
    Program_Disabled: typeof import('./components/pages/Public/Program_Disabled.vue')['default']
    Region: typeof import('./components/pages/Public/Region.vue')['default']
    Region_List: typeof import('./components/pages/Public/Region_List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Season: typeof import('./components/pages/Public/Season.vue')['default']
    Warehouse: typeof import('./components/pages/Public/Warehouse.vue')['default']
    Warehouse_List: typeof import('./components/pages/Public/Warehouse_List.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
